"""Reports: Markdown for people, CSV for trackers, JSON for automation, and the check catalog."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Sequence

from cloud_checks import __version__
from cloud_checks.core.engine import FAIL, PASS, SKIPPED, Check, CheckResult, to_findings
from cloud_checks.core.findings import SEVERITIES, Finding, count_by_severity, severity_rank
from cloud_checks.core.output import md_table, to_json, write_csv, write_text

CLOUD_NAMES = {"aws": "AWS", "azure": "Azure", "gcp": "Google Cloud"}
BADGE = {"critical": "🟥 critical", "high": "🟧 high", "medium": "🟨 medium", "low": "🟦 low", "info": "⬜ info"}
CSV_FIELDS = ("severity", "check", "title", "resource", "region", "detail", "fix", "cis")


def _result_label(result: CheckResult) -> str:
    if result.status == FAIL:
        return f"❌ FAIL ({len(result.hits)})"
    return "✅ PASS" if result.status == PASS else "⚪ SKIPPED"


def summary_counts(results: Sequence[CheckResult]) -> dict[str, int]:
    return {status: sum(1 for r in results if r.status == status) for status in (PASS, FAIL, SKIPPED)}


def render_markdown(snapshot: dict[str, Any], results: Sequence[CheckResult], source: str) -> str:
    cloud = CLOUD_NAMES.get(snapshot.get("cloud", ""), snapshot.get("cloud", ""))
    account = snapshot.get("account") or {}
    findings = to_findings(results)
    severities = count_by_severity(findings)
    counts = summary_counts(results)
    lines = [f"# {cloud} security check", "",
             f"**Scope:** {account.get('name') or account.get('id') or 'unknown'}"
             + (f" ({account['id']})" if account.get("name") and account.get("id") != account.get("name") else "")
             + f" · **Captured:** {snapshot.get('captured_at')} · **Source:** {source}", "",
             "## Summary", "",
             f"{counts[PASS]} checks passed, {counts[FAIL]} failed, {counts[SKIPPED]} skipped. "
             f"{len(findings)} finding(s).", "",
             md_table(["Severity", "Findings"], [(BADGE[s], severities[s]) for s in SEVERITIES]), "",
             "## Check results", "",
             md_table(["Check", "Service", "Severity", "CIS", "Result"],
                      [(f"`{r.check.id}`", r.check.service, r.check.severity, r.check.cis or "-", _result_label(r))
                       for r in results]), "", "## Findings", ""]
    failed = [r for r in results if r.status == FAIL]
    if not failed:
        lines.append("No findings. 🎉")
    def worst(result: CheckResult) -> int:
        return min(severity_rank(h.severity or result.check.severity) for h in result.hits)

    for result in sorted(failed, key=lambda r: (worst(r), r.check.id)):
        chk = result.check
        lines += [f"### {chk.title} ({len(result.hits)})", "",
                  f"`{chk.id}`" + (f" · CIS {chk.cis}" if chk.cis else ""), "",
                  f"**Why it matters:** {chk.why}", "", f"**Fix:** {chk.fix}", "",
                  md_table(["Severity", "Resource", "Region", "Detail"],
                           [(BADGE[h.severity or chk.severity], h.resource, h.region or "-", h.detail)
                            for h in result.hits]), ""]
    skipped = [r for r in results if r.status == SKIPPED]
    notes = snapshot.get("errors") or {}
    if skipped or notes:
        lines += ["## Coverage notes", ""]
        if skipped:
            lines += ["These checks did not run, so a clean result here is not a clean account:", ""]
            lines += [f"- `{r.check.id}`: {r.reason}" for r in skipped]
            lines.append("")
        partial = {k: v for k, v in notes.items() if not any(k in r.check.needs for r in skipped)}
        if partial:
            lines += ["Data that was only partly collected:", ""]
            lines += [f"- {key}: {value}" for key, value in sorted(partial.items())]
            lines.append("")
    lines += ["---", f"Generated by cloud-security-checks {__version__}. Read-only: nothing was changed."]
    return "\n".join(lines)


def to_payload(snapshot: dict[str, Any], results: Sequence[CheckResult], source: str) -> dict[str, Any]:
    findings = to_findings(results)
    return {"tool": "cloud-security-checks", "version": __version__,
            "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "cloud": snapshot.get("cloud"), "account": snapshot.get("account"),
            "captured_at": snapshot.get("captured_at"), "source": source,
            "summary": {"checks": summary_counts(results), "findings": count_by_severity(findings)},
            "checks": [{"id": r.check.id, "service": r.check.service, "severity": r.check.severity,
                        "cis": r.check.cis, "title": r.check.title, "status": r.status,
                        "findings": len(r.hits), "reason": r.reason} for r in results],
            "findings": [f.to_dict() for f in findings], "coverage_notes": snapshot.get("errors") or {}}


def write_reports(out_dir: Path, stem: str, formats: Sequence[str], snapshot: dict[str, Any],
                  results: Sequence[CheckResult], source: str) -> list[Path]:
    written: list[Path] = []
    if "md" in formats:
        path = out_dir / f"{stem}.md"
        write_text(path, render_markdown(snapshot, results, source))
        written.append(path)
    if "csv" in formats:
        path = out_dir / f"{stem}.csv"
        rows = [{"severity": h.severity or r.check.severity, "check": r.check.id, "title": r.check.title,
                 "resource": h.resource, "region": h.region, "detail": h.detail, "fix": r.check.fix,
                 "cis": r.check.cis} for r in results for h in r.hits]
        write_csv(path, rows, CSV_FIELDS)
        written.append(path)
    if "json" in formats:
        path = out_dir / f"{stem}.json"
        write_text(path, to_json(to_payload(snapshot, results, source)))
        written.append(path)
    return written


def print_summary(results: Sequence[CheckResult], paint: Callable[[str, str], str], limit: int = 15) -> None:
    findings: list[Finding] = to_findings(results)
    counts = summary_counts(results)
    severities = count_by_severity(findings)
    print(f"Checks: {counts[PASS]} passed, {counts[FAIL]} failed, {counts[SKIPPED]} skipped")
    print("Findings: " + ", ".join(paint(s, f"{severities[s]} {s}") for s in SEVERITIES if s != "info"))
    for f in findings[:limit]:
        print(f"  {paint(f.severity, f'[{f.severity:<8}]')} {f.title}: {f.target}")
    if len(findings) > limit:
        print(f"  ... and {len(findings) - limit} more in the report")


def catalog_markdown(checks: Sequence[Check]) -> str:
    """The check catalog (docs/CHECKS.md). Generated; a test keeps it in sync with the code."""
    lines = ["# Check catalog", "",
             f"_{len(checks)} checks. Generated by `cloud-checks list --format md`; do not edit by hand._", "",
             "CIS numbers refer to CIS AWS Foundations v3.0.0 and CIS Microsoft Azure Foundations v2.0.0, and "
             "are shown only where verified against the provider's published mapping.", ""]
    for cloud in ("aws", "azure", "gcp"):
        mine = [c for c in checks if c.cloud == cloud]
        if not mine:
            continue
        lines += [f"## {CLOUD_NAMES[cloud]} ({len(mine)})", "",
                  md_table(["Check", "Service", "Severity", "CIS", "What it finds", "Why it matters", "Fix"],
                           [(f"`{c.id}`", c.service, c.severity, c.cis or "-", c.title, c.why, c.fix) for c in mine]),
                  ""]
    return "\n".join(lines).rstrip() + "\n"
